//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Notes
    {
        public long note_id { get; set; }
        public Nullable<long> customer_id { get; set; }
        public Nullable<System.DateTime> note_date { get; set; }
        public string note_text { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
