//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interaction
    {
        public long interaction_id { get; set; }
        public Nullable<long> customer_id { get; set; }
        public string interaction_type { get; set; }
        public Nullable<System.DateTime> interaction_date { get; set; }
        public string description { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
