//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reply
    {
        public long replie_id { get; set; }
        public string staff { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public byte[] created_at { get; set; }
        public Nullable<long> ticket_id { get; set; }
    
        public virtual Support_Tickets Support_Tickets { get; set; }
    }
}
